version: '3.9'

services:
  postgres:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
  hydra-migrate:
    image: ghcr.io/aardvarkllc/test-hydra:0.0.1
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - postgres
  test-hydra:
    image: ghcr.io/aardvarkllc/test-hydra:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]

networks:
  intranet:
    name: intranet
    driver: overlay
